apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: test-node1
  description: Service test-node1

  annotations:
    github.com/project-slug: Backstage-GoldenImage/test-node1
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: Backstage_GoldenImage/test-node1/main
    argocd/app-name: test-node1
    backstage.io/kubernetes-id: test-node1
    backstage.io/kubernetes-namespace: default

spec:
  type: service
  owner: development
  lifecycle: experimental
